version = 0.1

[default.deploy.parameters]
stack_name = "matrix-calculator"
resolve_s3 = true
s3_prefix = "matrix-calculator"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
